### ISSUE TITLE
Connects and Quits not logged if audit_record_objs contains tables

### ISSUE THREAD

**Issue by RickPizzi** [mcafee/mysql-audit#101]
I noticed that Connects and Quits are only logged if audit_record_objs = ""
If you put anything there (eg. audit_record_objs = "schema.table" those are no longer logged.
Is it possible to have both login/logout and specific table command logged at same time?

Thank you
Rick

**Comment by guylichtman** [comment]
Hi,

You can use the special sequence: "{}". This includes also the empty set. For example you can specify:

`audit_record_objs="test.*,{}"`

I am also updating the wiki to better reflect this.

**Comment by RickPizzi** [comment]
Wouldn't that enable logging of other unrelated schemas and tables?

Thanks,
Rick
-- 
Riccardo Pizzi
pizzi@leopardus.com
http://www.vecchiflipper.it
http://www.pinballowners.com/webmaster

Dogs have masters. Cats have staff.

**Comment by RickPizzi** [comment]
Yes, it does, just tried�. 
-- 
Riccardo Pizzi
pizzi@leopardus.com
http://www.vecchiflipper.it
http://www.pinballowners.com/webmaster

Dogs have masters. Cats have staff.

**Comment by RickPizzi** [comment]
Just to be more clear:

set global audit_record_objs="myschema.CREDIT_CARD,myschema.BANK,{}"  
set global audit_record_cmds = select,connect,quit

Will cause ALL selects to be logged, and not only the two tables specified.
I need to log ALL login/logouts and ONLY those two tables...

Thanks,
Rick

**Comment by RickPizzi** [comment]
Looking better, it seems to cause  selects non involving specific tables to be listed.

Eg: 

"cmd":"select","query":"SELECT 1"
"cmd":"select","query":"SELECT @@session.tx_isolation"

**Comment by guylichtman** [comment]
There isn't an option to filter out selects with no objects and still get the connect and quit commands. The way it works if `{}` is specified as a paramater to audit_record_objs, then any statement executed which doesn't affect an object (such as "select 1") will be logged.

**Comment by RickPizzi** [comment]
hmmm. shouldn't be too hard to implement....
you could make it a special option, eg.  audit_record_logins = ON that when set,  automatically logs all records of type Connect and Quit, regardless the content of audit_record_cmds .

Unfortunately, SELECT 1 is very commonly used as a way for applications to check for available connection (sort of a keepalive) and it really floods the logs if I use {} as you suggested....

Thanks,
Rick

**Comment by RickPizzi** [comment]
Just modified the code to do the above :-) 
I sent a pull request. Please review it. Thanks!

**Comment by guylichtman** [comment]
Thanks for the pull request. Will review and comment there.

**Comment by guylichtman** [comment]
I've done a commit with some small modifications to the original PR. Binary build is available at: https://bintray.com/mcafee/mysql-audit-plugin/dev-snapshot/

**Comment by guylichtman** [comment]
Closing issues. If you still have questions or comments feel free to re-open.
