### ISSUE TITLE
It is a question about audit-plugin of MySQL. 

### ISSUE THREAD

**Issue by dms-sunnet2013** [mcafee/mysql-audit#104]
When there are updating etc. to DB, is the log outputted instancy? 
The present condition is not outputted instancy. 

Previously, there are answers to the above questions,
Although we confirmed your designated site,
Place of applicable was not found.
Te Accordingly, shareholders page URL described locations in the site,
Or Could you tell me the audit log output conditions.
As the current situation,
conditions are specified in my.cnf it meets but,
It is a situation that is not output at any time.

**Comment by guylichtman** [comment]
I am not sure I am fully following your question. Can you provide some examples. 

thanks,

Guy

**Comment by dms-sunnet2013** [comment]
Before I had a response to a question of "the audit log output condition" from you.
I confirmed the site of designation based on the answer, but a relevant part wasn't found.
Therefore please tell me mentioning point Uniform Resource Locator in the site or the audit log printout condition.

The condition that it's designated as "my.cnf" is met as the present state, but when renewing, it isn't output at any time.

**Comment by guylichtman** [comment]
Can you provide some examples and logs.

**Comment by guylichtman** [comment]
Closing issue as no response.
