### ISSUE TITLE
[Question] How to mask query string?

### ISSUE THREAD

**Issue by ggeligible** [mcafee/mysql-audit#109]
Hello Team,

Is it possible to mask query string for a given object/command combination. Something like mask query for all insert on a particular table.

Thanks,
GG

**Comment by guylichtman** [comment]
Hi, 

We have support for password masking but this can be configured to pretty much mask any statement. It works with a regex. Take a look at: https://github.com/mcafee/mysql-audit/wiki/Configuration and the 2 relevant configuration params are: `audit_password_masking_cmds` and `audit_password_masking_regex` .

**Comment by ggeligible** [comment]
Thanks Guy for your suggestion. Password masking regex makes sense, will use that.
