### ISSUE TITLE
/usr/bin/mysqladmin: Unknown command: 'set global audit_json_file_flush=on'

### ISSUE THREAD

**Issue by nlong12** [mcafee/mysql-audit#111]
Good afternoon
Have installed the mysql-audit utility, here is the my.cnf file
#Mcafee audit variables
plugin-load=AUDIT=libaudit_plugin.so
audit_json_file=1
audit_json_log_file=/var/lib/mysqllogs/mysql-audit.json
audit_record_cmds=insert,update,delete,connect,failed,quit,CREATE_USER,GRANT,SET_OPTION,SLAVE_START,CREATE_SERVER,ALTER_SERVER,CHANGE_MASTER,CREATE_TABLE,DROP_TABLE

Here is my logrotate script
/var/lib/mysqllogs/mysql-audit.json {
create 644 mysql mysql
notifempty
daily
rotate 5
missingok
nocompress
sharedscripts
postrotate
# run if mysqld is running
#if test -n "`ps acx|grep mysqld`"; then
#/usr/bin/mysqladmin "SET GLOBAL audit_json_file_flush=on"
#/sbin/service mysqld reload
#fi
endscript
}

When I run the script I get the following error:
/usr/bin/mysqladmin: Unknown command: 'set global audit_json_file_flush=on'    Have attempted numerous options: 1. SET GLOBAL in upper case, ON in upper case nothing works.

Here is my version of mysql:
Server version: 5.5.41-log Distributed by The IUS Community Project
Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.

Would greatly appreciate some help in resolving this issue.

Thank you!

Norm

**Comment by guylichtman** [comment]
You need to use the "mysql" client. mysqladmin doesn't support running "set
global ..".

You can run the following:

echo "set global audit_json_file_flush=on;" | mysql -u root

**Comment by nlong12** [comment]
Thank you for your response that did the trick.

Norm
