### ISSUE TITLE
Compiling.txt missing compile step

### ISSUE THREAD

**Issue by utdrmac** [mcafee/mysql-audit#112]
Under 5.1 instructions, there is no step to tell you to compile MySQL first before compiling the plugin and you have to do this.

**Comment by guylichtman** [comment]
I just looked and it says the following under 5.1:

```
cd mysql-5.1.40
CXX=gcc ./configure
cd include
make
```

Which is what we run before compiling the plugin.

**Comment by utdrmac** [comment]
Ugh. I must have missed this. Sorry.
