### ISSUE TITLE
Configuration Documentation Mismatch

### ISSUE THREAD

**Issue by utdrmac** [mcafee/mysql-audit#115]
The code shows this:

```
static MYSQL_SYSVAR_STR(whitelist_cmds, whitelist_cmds_string,
			PLUGIN_VAR_RQCMDARG,
			"AUDIT plugin commands to skip, comma separated",
			NULL, whitelist_cmds_string_update, NULL);
static MYSQL_SYSVAR_STR(record_cmds, record_cmds_string,
			PLUGIN_VAR_RQCMDARG,
			"AUDIT plugin whitelisted commands for which queries are not recorded, comma separated",
			NULL, record_cmds_string_update, NULL);
```

The above says "audit_record_cmds" is a whitelist-style setting. But the documentation (wiki/Configuration) says "Comma separated list of commands to log to the audit trail."

So which is it? It seems I'm getting audit logging regardless of the setting.

**Comment by utdrmac** [comment]
Documentation also states that 'audit_record_objs' should be listed using dot-notation. However, I've found that setting "*.*" leaves out almost 50% of the queries. Setting this to empty string gets everything.

**Comment by guylichtman** [comment]
Thanks for reporting this. We will put in a fix in the description in the
code.

**Comment by billakantisatish** [comment]
When the v1.0.9 will be released?

**Comment by aharonrobbins** [comment]
1.0.9 should be released by the end of Q1 2016.

Thanks,

Aharon

Aharon (Arnold) Robbins
Senior Software Engineer
Sensor - Database Security
McAfee. Part of Intel Security.
[cid:image003.png@01CF5AF2.16A4D380]
