### ISSUE TITLE
Installing audit plugin failed, Failed parsing audit_offsets

### ISSUE THREAD

**Issue by mcafee-oduarte** [mcafee/mysql-audit#117]
Hi, 

I follow all the installation indications but an error appears in the log.

MySLQ server: 5.6.25 MySQL Community Server
Plugin: audit-plugin-mysql-5.6.1.0.7-509-linux-x86_64
OS: Centos 6.6, Kernel 2.6.32-504.elx86_64

![capture1](https://cloud.githubusercontent.com/assets/13025380/8320226/af704cec-19dd-11e5-9089-504cdb7caa96.PNG)

I run the script and take the offsets values from it:

![capture2](https://cloud.githubusercontent.com/assets/13025380/8320261/25c8dd1e-19de-11e5-8a9c-2499d9612ab2.PNG)

But the error continues, any ideas?

Regards,

Oscar

**Comment by guylichtman** [comment]
The script changed between version 1.0.7 and 1.0.8 (explained in the wiki).
You might be using the wrong script. Anyway, you should use version 1.0.8
of the plugin as it contains some important fixes. Furthermore, latest dev
snapshot contains the offsets built-in so I suggest using that version. You
can download it at:

https://bintray.com/mcafee/mysql-audit-plugin/dev-snapshot/

**Comment by mcafee-oduarte** [comment]
Thanks Guy for your help, I downloaded the last dev snapshot and I works well
