### ISSUE TITLE
error broken pipe when using socket server

### ISSUE THREAD

**Issue by chenzhe07** [mcafee/mysql-audit#120]
I wrote a socket server to recieve the audit log and the broken pipe error occured every 10 sec (determined by audit_json_socket_retry) in mysql error log file when MySQL server enable the mysql-audit socket, and the audit log can be displayed, but there may be missing(lose 10 sec audit data)， as the error message in mysql error log:

```
Aug 14 13:55:00 cz mysqld-3306: 150814 13:55:00 [Note] Audit Plugin: success opening socket: /web/mysql/node3306/data/s_audit.
Aug 14 13:55:00 cz mysqld-3306: 150814 13:55:00 [ERROR] Audit Plugin: failed writing to socket: /web/mysql/node3306/data/s_audit. Err: Broken pipe
Aug 14 13:55:11 cz mysqld-3306: 150814 13:55:11 [Note] Audit Plugin: success opening socket: /web/mysql/node3306/data/s_audit.
Aug 14 13:55:11 cz mysqld-3306: 150814 13:55:11 [ERROR] Audit Plugin: failed writing to socket: /web/mysql/node3306/data/s_audit. Err: Broken pipe
```
my system env:

```
DELL R610
centos 6.2
Percona MySQL Server 5.5.23-rel25.3
mysql-audit: 5.5-1.0.5-479 and 5.5-1.0.8-527
```

my socket server received audit log, and add some MySQL server info(such as internal ip and port), like this: 
```
{"server":"10.3.254.2","port":"3306","msg-type":"activity","date":"1439546377023","thread-id":"117199","query-id":"351853","user":"root","priv_user":"root","host":"localhost","cmd":"select","objects":[{"db":"test","name":"tb1","obj_type":"TABLE"}],"query":"select id, name from tb1 where id > 1000 limit 1"}
```
after modify the data, send it to the other server program which is the centralized server, I think the reason of the above error message is because socket server can't handle huge data without delay and there is no error when I remove the send modify data function or test with small amount of sql(10/sec) . Maybe my guess is wrong, but mysql audit can ignore the signal SIGPIPE or pipe error to reduce loss data between the audit_json_socket_retry time.

Are there any other reasons can cause this error?  thanks for your help.

**Comment by guylichtman** [comment]
I am guessing you are doing something wrong with your socket server. I suggest trying to take a look at syslog-ng. It has the capability of accepting events over a socket. You can check out a small blog post I wrote about this at: http://lichtman.io/mcafee-mysql-audit-plugin-logging-to-syslog-ng/ .

**Comment by chenzhe07** [comment]
thanks @guylichtman , I refactor server socket, and fixed this error, I'll try to use syslog-ng with mysql-audit
