### ISSUE TITLE
Question: Support for MySQL 5.7

### ISSUE THREAD

**Issue by ankitthakwani** [mcafee/mysql-audit#122]
Hi,

I understand that MySQL 5.7 is still not GA but was wondering if audit plugin is compatible with it.

**Comment by guylichtman** [comment]
Mysql 5.7 is still not supported. We have plans to start testing 5.7 soon,
but so far I can't report if there are any issues or not.

**Comment by ankitthakwani** [comment]
Hi Guy,

Do you have a test release which I might use to test 5.7?

**Comment by guylichtman** [comment]
Not yet. We are working on 5.7 support. It will probably take a few more
weeks.

**Comment by Pasha167** [comment]
We are also looking for 5.7 support. 
Hope it will come soon.

**Comment by aharonrobbins** [comment]
Hi. We are working on 5.7 support and it's making progress.  We hope to have something soon.

**Comment by ttszk** [comment]
:+1:

**Comment by aharonrobbins** [comment]
We have made good progress. Coming Real Soon Now.  Thanks for your patience.

**Comment by maver1ck** [comment]
:+1:

**Comment by aharonrobbins** [comment]
The current code base (just pushed to github) has support for MySQL 5.7, starting at 5.7.9. Please try it out.  Thanks!
