### ISSUE TITLE
Install and Uninstall Plugin without Restart

### ISSUE THREAD

**Issue by atze234** [mcafee/mysql-audit#123]
Hi,
im trying to temporarily add the audit Plugin to a Database to find "unused" Mysql-Users. Im loading and configuring the Plugin with INSTALL PLUGIN ... and SET GLOBAL audit... without a mysqld restart.

After a few days i've found all the unused Users and want to uninstall the Plugin. As far as i can see its not possible to do this without a restart of mysqld, is that right or am i missing something? 

At the moment i'm thinking about those 2 ways:
- set audit_uninstall_plugin in my.cnf -> restart -> uninstall -> clear my.cnf [-> optional restart]
- truncate mysql.plugin -> restart

Thank you
Jörg

**Comment by guylichtman** [comment]
If you didn't set audit_uninstall_plugin in my.cnf before installing the plugin then it is not possible to uninstall via UNINSTALL PLUGIN. It is an added measure of protection we added. 

Option 2 will work for you in your case: delete the entry AUDIT entry from mysql.plugin table and then restart.

**Comment by atze234** [comment]
Hi Guy,
thank you, that did the trick.
Add audit_uninstall_plugin in my.cnf before installing the plugin. I thought i have to restart mysqld then, but thats not the case. 

So for "temporary" Audit Workflow:
- add audit_uninstall_plugin=1 to my.cnf
- Install Plugin
- Audit...
- uninstall plugin
- remove audit_uninstall_plugin=1 from my.cnf (important, since mysql wont restart with this option in my.cnf)

**Comment by selvackp** [comment]
Hey you just disable logging parameters ,thats enough ..
