### ISSUE TITLE
It can not be filtered from the library from the main library synchronous operation

### ISSUE THREAD

**Issue by yayun826** [mcafee/mysql-audit#124]
Hello, I found the log will record operating synchronized from the main library from the library, the unusually large amount of logs, want to improve.

**Comment by guylichtman** [comment]
Can you provide some more details. Not sure what you are after.

**Comment by yayun826** [comment]
mysql replication slave master-slave replication thread recorded operating, hoping to filter out. I set up the parameters audit_whitelist_users = '"",' also invalid.

**Comment by guylichtman** [comment]
You can try using:

    audit_whitelist_users={}

To filter out the empty user.

**Comment by yayun826** [comment]
Thank you
