### ISSUE TITLE
Is MySQL Audit Plugin compatible with the license of MySQL Standard/Enterprise Edition?

### ISSUE THREAD

**Issue by kubo** [mcafee/mysql-audit#126]
(Edited: "the license of" was added in two places after the reply of guylichtman.)

MySQL Audit Plugin is licensed under GPL v2. It is obviously compatible with the license of MySQL Community Edition.
Is it, however, compatible with the license of MySQL Standard/Enterprise Edition?

If it isn't and the incompatibility is involuntary, could the license be changed to LGPL or [GPL with a special exception](http://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs)?

**Comment by guylichtman** [comment]
The McAfee MySQL Audit plugin is compatible with MySQL enterprise. You can simply install it in MySQL enterprise the same way you would with MySQL community edition. 

Not sure why you are concerned with the license and compatibility.

**Comment by kubo** [comment]
I'm concerned with the compatibility of licenses.

In http://www.gnu.org/licenses/gpl-faq.en.html#GPLPluginsInNF

> This means that combination of the GPL-covered plug-in with the non-free main program would violate the GPL.

Is the license of MySQL enterprise edition is the GPL?
Oracle provides MySQL under a [dual license model](http://www.mysql.com/about/legal/licensing/oem/). One is the GPL and the other is a commercial license.
I found a page saying that [MySQL community edition is available under the GPL](https://www.mysql.com/products/community/).
However I cannot found such a page about MySQL enterprise edition.
If MySQL enterprise edition is released under a commercial license, that combination of the
MySQL Audit plugin with MySQL enterprise edition violates the GPL.

**Comment by kubo** [comment]
> If MySQL enterprise edition is released under a commercial license, combination of the
MySQL Audit plugin with MySQL enterprise edition violates the GPL.

Strictly speaking, if Oracle's commercial license were compatible with the GPL, combination of a GPL-covered plugin didn't violate the GPL.

**Comment by guylichtman** [comment]
As far as I understand, the license issue your are describing is only relevant if you are distributing Oracle Enterprise Edition to customers (ISV, OEM). In that case, you won't be able to distribute Oracle Enterprise Edition together with GPL code (in this case the audit plugin). 

Disclaimer: I am not a lawyer. I may be wrong.

**Comment by kubo** [comment]
According to [this FAQ entry](http://www.gnu.org/licenses/gpl-faq.en.html#MoneyGuzzlerInc), distributing GPL-covered software linked with a proprietary file is not permitted. Though it doesn't say whether distributing the GPL-covered software together with the proprietary file or separately from the proprietary file, I bet that FSF says that it is not permitted in both cases. Otherwise the consequence is definitely something FSF want to avoid. Thus, IMO, distributing the audit plugin (GPL-covered software) linked with MySQL enterprise edition (proprietary program), even though they are separately distributed, is not permitted in FSF's point of view.

I don't think FSF is 100% correct. McAfee may have different opinion. For example [opinions different from FSF exist on linking GPL software with GPL-incompatible software](https://en.wikipedia.org/wiki/GNU_General_Public_License#Libraries).

Well, could you add your opinion in a document about coverage of the GPL as [linux kernel](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/plain/COPYING) does?

Disclaimer: I am not a lawyer also. Nobody knows the answer without clear court decisions.

**Comment by guylichtman** [comment]
Do you have a specific use case you are after? Can you share? It would help to better understand what you are trying to achieve.

**Comment by kubo** [comment]
> Do you have a specific use case you are after? Can you share?

Sure!

If I make a product which gathers outputs of the audit plugin, can I guide users to install the audit plugin into MySQL Enterprise Edition?
I have no will to distribute MySQL Enterprise Edition.
I may or may not distribute pre-compiled audit plugin with the product.
The license of the audit plugin doesn't affect the license of the product because they run in separate processes.
If I need to change the audit plugin for requirements of the product, the modified parts will be open under the GPL because it is a derived work.
What I worry about is whether the audit plugin and MySQL enterprise edition are legally compatible.

**Comment by guylichtman** [comment]
From what you describe it sounds OK.  As long as you don't distribute MySql
enterprise together with GPL code. So if you are not distributing MySql
enterprise, I would say you are good.

**Comment by kubo** [comment]
Thank a lot!

Could you add your opinion in a document?
If a user have a question about the GPL, he will firstly see the license itself and then see [this FAQ](http://www.gnu.org/licenses/gpl-faq.en.html). When your opinion is different from the FAQ (I think so), it should be documented.

I have a new related question.
"together with" looks like the key point in your opinion. How about a product which uses the output of a GPL software? Which is your opinion?

1. Distributing the product and the GPL software in a package is permitted.
2. Distributing them in a package is not permitted. Distributing them in two separate packages is permitted.
3. Distributing them by one distributor is not permitted even though they are in separate packages.

IMO, as long as the product and the GPL software are separate parts of an ["aggregate"](http://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation), distributing them in a package is permitted.
However, you may have other opinion. I want to confirm your opinion just to be sure.

**Comment by guylichtman** [comment]
I don't have an opinion that differs from the GPL and it's FAQ. Regarding your question, it is more an issue on how your company treats the GPL and under what license you release the "aggregate". GNU has a good faq entry about this: http://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation .

**Comment by kubo** [comment]
> I don't have an opinion that differs from the GPL and it's FAQ.

Hmm, as for distributing a GPL software dynamically linked with a proprietary software,
though you think that your opinion is same with the GPL and its FAQ, I don't think so.
Could you teach me information source of your opinion? I have read the FAQ several times
and I wrote my thought in https://github.com/mcafee/mysql-audit/issues/126#issuecomment-153335401.
I cannot change my though without reason but may change it by credible information source.

My goal is simple. Just using the audit plugin with a commercially licensed MySQL server legally.

> Regarding your question, it is more an issue on how your company treats the GPL and under what license you release the "aggregate". GNU has a good faq entry about this: http://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation .

What issue? What statements in the FAQ entry are relevant to the issue?
I have already read the entry. So I made a link to the entry in my previous post https://github.com/mcafee/mysql-audit/issues/126#issuecomment-154414994 to tell the meaning of "aggregate" in the context.
Could you choose from the three options in my previous post to know your opinion?
If you choose 1, there is no disagreement. If 2, I won't agree but respect your choice because the audit plugin is yours.

**Comment by guylichtman** [comment]
It is hard for me to answer your question regarding 1 or 2 as it depends upon how you license the "aggregate". As stated in the FAQ: `The only condition is that you cannot release the aggregate under a license that prohibits users from exercising rights that each program's individual license would grant them.` So if you follow the FAQ statement, I would say that 1 is ok. 

I have to repeat my disclaimer: I am not a lawyer. I may be wrong.

**Comment by kubo** [comment]
> It is hard for me to answer your question regarding 1 or 2 as it depends upon how you license the "aggregate". As stated in the FAQ: `The only condition is that you cannot release the aggregate under a license that prohibits users from exercising rights that each program's individual license would grant them.` So if you follow the FAQ statement, I would say that 1 is ok

Thanks for your reply. It is not an issue. I'll add document which states that "The McAfee MySQL Audit Plugin is licensed under the GPL" and "The license of this product doesn't cover the audit plugin" to follow the FAQ statement.

The question asked in https://github.com/mcafee/mysql-audit/issues/126#issuecomment-154414994 was solved. The rest issue is whether a GPL software (the audit plugin) can be used with a proprietary software (MySQL Enterprise Edition) legally when they are dynamically linked.

Summary of my opinion is:
* It is not permitted in view of the FAQ. The FAQ says that ["If modules are designed to run linked together in a shared address space, that almost surely means combining them into one program"](http://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation) and ["The GPL says that the whole combined program has to be released under the GPL."](http://www.gnu.org/licenses/gpl-faq.en.html#GPLModuleLicense)
* It is permitted if GPL software's license is changed to the LGPL or [GPL with a special exception](http://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs).
* It is permitted if the coverage of the GPL is stated differently from the FAQ as the linux kernel states that ["This copyright does **not** cover user programs that use kernel
 services by normal system calls."](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/plain/COPYING)
* When author's opinion is different from the GPL FAQ, it should be documented.

Your opinion is:
* It is not permitted if MySql enterprise is distributed together with GPL code.
* It is permitted if MySql enterprise is not distributed together with GPL code.
* This opinion isn't different from the GPL and its FAQ.

We don't reach an agreement about this issue.

I'm uncertain about your opinion. I guess some interpretations of the GPL which may fit your opinion but it is just a guess and I have not seen such interpretations.
However, I'll close this issue because the copyright holder, McAfee, says that it is okay as long as I don't distribute MySQL Enterprise Edition.
Even if the opinion isn't correct, no problem will be raised as long as copyright holders don't complain about it.
