### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by ValerieNC** [mcafee/mysql-audit#127]
I've tried several versions, but get the same error on installation.

This is extracted from audit-plugin-mysql-5.6-1.0.8-527-linux-x86_64.zip:

[root@centosbase plugin]# pwd
/usr/lib64/mysql/plugin
[root@centosbase plugin]# ls -al | grep libaudit
-rwxr-xr-x. 1 root root 1363697 Nov  2 22:24 libaudit_plugin.so

Here is the error:
mysql> INSTALL PLUGIN AUDIT SONAME 'libaudit_plugin.so';
ERROR 1126 (HY000): Can't open shared library '/usr/lib64/mysql/plugin/libaudit_plugin.so' (errno: 2 /usr/lib64/mysql/plugin/libaudit_plugin.so: cannot open shared object file: Permission denied)

Server info:
mysql> status
--------------
mysql  Ver 14.14 Distrib 5.6.26-74.0, for Linux (x86_64) using  6.2

Connection id:		2
Current database:
Current user:		root@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.6.26-74.0 Percona Server (GPL), Release 74.0, Revision 32f8dfd
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	latin1
Db     characterset:	latin1
Client characterset:	utf8
Conn.  characterset:	utf8
UNIX socket:		/var/lib/mysql/mysql.sock
Uptime:			3 min 37 sec

Threads: 1  Questions: 16  Slow queries: 0  Opens: 68  Flush tables: 1  Open tables: 61  Queries per second avg: 0.073
--------------

[root@centosbase plugin]# cat /etc/*release*
CentOS Linux release 7.1.1503 (Core)

---------
This is a VM running locally.

Any idea what could be wrong?

**Comment by selvackp** [comment]
Check your permissions of plugin directory might be its in read only mode

**Comment by ValerieNC** [comment]
Thanks, selvackp! I checked, and that doesn't seem to be it.

**Comment by selvackp** [comment]
https://bugs.mysql.com/bug.php?id=27258

Itseems help to you

Regards,

SelvaKumar

*Be better then you were yesterday*

**Comment by ValerieNC** [comment]
Thanks -- taking a look.

**Comment by selvackp** [comment]
Have you checked your directory mysql user has all access ?

Regards,

SelvaKumar

*Be better then you were yesterday*

**Comment by ValerieNC** [comment]
I did. I also just installed another plugin successfully as a test. 

I'm going to try a different distro in case it's a Centos 7 conflict (I see the other issue about Solaris).

**Comment by selvackp** [comment]
Thats Good News :)

Regards,

SelvaKumar

*Be better then you were yesterday*

**Comment by guylichtman** [comment]
Any update?

**Comment by ValerieNC** [comment]
I beat on it quite a bit, but did not get it to install.

**Comment by guylichtman** [comment]
Take a look at /var/log/audit/audit.log . Do you see there any errors or messages related to mysqld or libaudit_plugin.so from when you tried to install the plugin?

**Comment by ValerieNC** [comment]
Thanks, Guy. I've already deleted the VM related to my testing. :) Thank you for trying to help, though! Will come back if I have another round of testing. IIRC the log said the same thing as the error on the command line, though.

**Comment by guylichtman** [comment]
Sure. Closing issue. If you encounter again feel free to re-open.
