### ISSUE TITLE
Meaning of audit_header_msg option.

### ISSUE THREAD

**Issue by tommyilpazzo** [mcafee/mysql-audit#129]
Hi,
I've some questions about how the audit_header_msg option works in order to decide if I really need it or not.

What's the event that trigger the write of a new element with msg-type=header? 
How many time is it written (frequency)?
What kind of information can I get from a header message?

Thank you

Regards,
Tommaso

**Comment by guylichtman** [comment]
It is written at the start of a logging file or write after connecting to a socket. Additionally, if you flush the log (using: `audit_json_file_flush`), it will be written when the file is re-opened.

**Comment by tommyilpazzo** [comment]
Thank you for the quick answer.
