### ISSUE TITLE
Query logged when setting audit_force_record_logins=ON

### ISSUE THREAD

**Issue by tommyilpazzo** [mcafee/mysql-audit#130]
Hi,
I'm experiencing a strange behaviour when setting the audit_force_record_logins option to ON. The problem is that if I don't set the audit_record_cmds option all query are logged, while I was expecting only connect, quit and failed login commands to be logged.
The problem  seems to be solved by setting the audit_record_cmds=connect,quit,failed login.
Maybe I didn't understand well how the audit_force_record_logins option is supposed to work.
Am I wrong?

Thank you for the great job.

Regards,
Tommaso

**Comment by guylichtman** [comment]
It is really only relevant if you are using: `audit_record_objs`. In that case when you set `audit_force_record_logins` even if you set a value for `audit_record_objs`, that value will not limit logging: connect,quit and failed login.

**Comment by tommyilpazzo** [comment]
Thank you for the clarification.
