### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by yayun826** [mcafee/mysql-audit#131]
Hello, audit plug-in gives serious performance degradation, set the parameters which reduce the impact on performance?

**Comment by selvackp** [comment]
Hey,

Please do the below things ,

1.Log the file in different mount than data file mount
2.Don't log all items, critical is drop and delete is it more enough
3.Rotate log by each day or an hour

This might help you , Please tell us where you feeling performance issue ?


Regards,

SelvaKumar

*Be better then you were yesterday*

**Comment by yayun826** [comment]
My configuration is as follows:
audit_offsets=6024, 6072, 3776, 4200, 88, 2568, 8, 0, 16, 24, 120, 6144
audit_whitelist_users='{}'
audit_record_cmds='insert,update,delete,select,alter,create,drop,call'
audit_json_file=1
audit_uninstall_plugin=1
Do you have any suggestions for me optimization?

**Comment by guylichtman** [comment]
Can you share your results?

In general the more you can filter using the various config options the
better the results will be.

**Comment by guylichtman** [comment]
Closing issue as no response.
