### ISSUE TITLE
Recording query duration?

### ISSUE THREAD

**Issue by blalor** [mcafee/mysql-audit#134]
Would it be possible to add how long a query/command took to execute, at least for some commands like select?

**Comment by aharonrobbins** [comment]
Hi. The audit plugin is intended for auditing - tracking what occurred. There are other logging facilities in MySQL that should let you get this information.  Therefore we don't plan to add such a feature, but if you or anyone else wishes to contribute a patch to do this, we will be glad to review it for inclusion.  Thanks.
