### ISSUE TITLE
"set global audit_json_file_flush=1" does not produce any change on the current log file.

### ISSUE THREAD

**Issue by luca83** [mcafee/mysql-audit#135]
Hi guys,
I'm try to rotate the log executing the command:

*set global audit_json_file_flush=1*
or
*set global audit_json_file_flush=ON*

but doesn't produce any effect on the current log file.
Below part of my.cnf configuration

```
[mysqld]
#.........other conf...
plugin-load=AUDIT=libaudit_plugin.so
audit_json_file=1
audit_json_socket_name=/tmp/audit.sock
audit_json_socket=OFF
audit_json_log_file=/var/log/mysql/audit.log
audit_record_cmds=connect,Quit,show,select,insert,update,delete
audit_validate_checksum=OFF
#...other conf....
```

Any ideas?
thank you all

**Comment by aharonrobbins** [comment]
Hi. This simply causes the plugin to flush data to the log file. You have to manually do the  rotation yourself. Quoting from http://dev.mysql.com/doc/refman/5.5/en/log-file-maintenance.html (emphasis mine): 

The server creates a new binary log file when you flush the logs. However, it just closes and reopens the general and slow query log files. _To cause new files to be created on Unix, rename the current log files before flushing them. At flush time, the server opens new log files with the original names._ For example, if the general and slow query log files are named mysql.log and mysql-slow.log, you can use a series of commands like this:

shell> cd mysql-data-directory
shell> mv mysql.log mysql.old
shell> mv mysql-slow.log mysql-slow.old
shell> mysqladmin flush-logs

Hope this helps!

**Comment by luca83** [comment]
Thank you very .. it work perfectly.
