### ISSUE TITLE
audit_whitelist_users for empty user 

### ISSUE THREAD

**Issue by fcnaveen** [mcafee/mysql-audit#139]
Hi Team, 

We were trying to restricting the SQL thread user in slave server. There is no sufficient info on wiki about empty user for whitelisting.  (We have gone through your code, we have found we can use {} for empty string ). Please update the wiki with below option 

ex: set global audit_whitelist_users='{}' ;

Regards
Naveen

**Comment by aharonrobbins** [comment]
Hi.

Thanks for the input! We will update the wiki.

Aharon

Aharon (Arnold) Robbins
Senior Software Engineer
Sensor - Database Security
McAfee. Part of Intel Security.
[cid:image003.png@01CF5AF2.16A4D380]

**Comment by karthik-gorthi** [comment]
Hello,

The Wiki / Notes should ideally include a way to escape logging the SQL thread's activity. Currently, the wiki does include a note on how to escape an empty user, but doesn't link that to the SQL thread.

Suggested Note:
- Plugin logs all activity performed by the SQL thread. To turn it off, set global audit_whitelist_users='{}' ;

**Comment by guylichtman** [comment]
Wiki page has been updated with a note about the sql thread in a slave server. 

Thanks for the feedback.
