### ISSUE TITLE
unknown variable 'audit-json-file-flush=1'

### ISSUE THREAD

**Issue by electrical** [mcafee/mysql-audit#140]
Hi,

I'm trying to implement the auditing with logrotate but when enabling the setting in the config file i get this error at startup:

2016-06-01 16:56:59 21123 [ERROR] /usr/sbin/mysqld: unknown variable 'audit-json-file-flush=1'

I'm also unable to set it via the `set global` way.

This is version 1.0.9 with mysql 5.6.25

cheers.

**Comment by guylichtman** [comment]
The setting is meant to be used during run-time to close and open the audit log file. You should execute it as:

`set global audit_json_file_flush=on;`

When it is executed you will see in the mysql error log following output:

```
[Note] Audit Plugin: success opening file: mysql-audit.json.
[Note] Audit Plugin: Log flush complete.
```

To roll over the log rename the log file before issuing the command. For example you can build a cron job which runs daily and runs the following:

```
mv /var/lib/mysql/mysql-audit.json /var/lib/mysql/mysql-audit.json.`date +%F`
mysql -e 'set global audit_json_file_flush=on;'
```

Of course, you can also setup logrotate to do this.with the `postrotate` action.

**Comment by electrical** [comment]
Ahh okay, the way i read it was it would be in sync with the mysqladmin flush-logs command for rotating it.
I guess the documentation is a bit unclear about the actual implementation.

**Comment by guylichtman** [comment]
I've added reference from the wiki to this issue for further clarifications.

**Comment by Jamalc0m** [comment]
Hello @electrical,
did you manage to create a cron job script for this ?
Thanks,

**Comment by electrical** [comment]
@Jamalc0m I think i have yeah. Let me check when i'm in work.

**Comment by Jamalc0m** [comment]
Thanks @electrical, I appreciate it.

**Comment by electrical** [comment]
@Jamalc0m I have implemented the following as it was easier:

```
/var/log/mysql/mysql-audit.json {
        daily
        copytruncate
        compress
        rotate 1
        dateext
        dateformat .%Y-%m-%d
}
```

**Comment by Jamalc0m** [comment]
@electrical, Can you please tell me where did you add this configuration?

Thanks,

**Comment by electrical** [comment]
I put this in the /etc/logrotate.d directory

**Comment by Jamalc0m** [comment]
@electrical Thanks for you support, i am really not that familiar with redhat, can you please check if this configuration correct, I would like to create every day new log , and the logs should be for 3 months:

/var/log/mysql/mysql-audit.json {
        daily
        copytruncate
        compress
        rotate 12
        dateext
        dateformat .%Y-%m-%d
}

**Comment by electrical** [comment]
The rotate 12 means you'll only have 12 days of files, you'll have to set that to 90 days then.

**Comment by Jamalc0m** [comment]
Thank you very much, I really appreciate your help :)

**Comment by Jamalc0m** [comment]
Hello @electrical,

I couldn't find /var/log/mysql/mysql-audit.json, Do I need to put the log file, the log which I have is
/var/log/mysql/audit.log 

That means the configuartion should be like this:

/var/log/mysql/audit.log{
daily
copytruncate
compress
rotate 12
dateext
dateformat .%Y-%m-%d
}

Please correct me if i am wrong.

Thanks again.

**Comment by electrical** [comment]
No problem, glad it solved your problem :-)

**Comment by Jamalc0m** [comment]
Hello @electrical,

Is there any UI interface for mcafee mysql audit plugin, I tried to search but I couldn't find anything.

Thanks in advance,

**Comment by aharonrobbins** [comment]
Hi.

There is no UI interface that we know of.  Configuration is via the my.cnf file and is pretty simple; you should be able to work with any text editor of your choice, such as nano or pico.

Hope this helps,

Aharon

Aharon (Arnold) Robbins
Senior Software Engineer
Sensor - Database Security
McAfee. Part of Intel Security.
[cid:image003.png@01CF5AF2.16A4D380]

**Comment by Jamalc0m** [comment]
Hi @aharonrobbins,
Thanks for the update, but i meant UI interface for the logs that are generated, so instead of viewing the logs by using the editor, its better to have an UI interface like ossec UI.

**Comment by aharonrobbins** [comment]
Thanks for the clarification.

Unfortunately, the answer is still that there is no UI that we know of.  Sorry.

Thanks,

Aharon

Aharon (Arnold) Robbins
Senior Software Engineer
Sensor - Database Security
McAfee. Part of Intel Security.
[cid:image003.png@01CF5AF2.16A4D380]

**Comment by vinayjaiswal1990** [comment]
Hi , 

I have implemented macafee audit log rotation using cron job but getting replication stop and it throw [Note] McAfee Audit Plugin: Log flush complete.
05:04:39 UTC - mysqld got signal 11 ;

Script content : 
AUDIT_LOG_FILE=`${mysql} -uxxxxx -pxxxxx ${socket} -NBe "Show variables;" | grep audit_json_log_file | grep file |   cut -f2`

TRIMMED_AUDIT_LOG_FILE=`echo ${AUDIT_LOG_FILE} | cut -d'.' -f1` 

mv ${AUDIT_LOG_FILE} ${TRIMMED_AUDIT_LOG_FILE}_${dt}.log && touch ${AUDIT_LOG_FILE} && chown mysql.mysql ${AUDIT_LOG_FILE} && ${mysql} -uxxxx -pxxxxx ${socket} -e "set global audit_json_file_flush=ON; set global audit_json_file_flush=OFF;"

gzip -9 ${TRIMMED_AUDIT_LOG_FILE}_${dt}.log

Please suggest what may cause for this so that i can debug further .
