### ISSUE TITLE
mysql audit version for mysql specific version.

### ISSUE THREAD

**Issue by zafermalik** [mcafee/mysql-audit#149]
There is no identification that for which mysql version we should use which plugin. As there are so many plugin for mysql5.6 so I am not able to identify that which plugin I should download for 5.6.34. If there is any mapping/info regarding this then help me or update such type information which will be helpfull for all of us.

I have also asked this problem on stakeoverflow as per below but also not getting any help.

http://stackoverflow.com/questions/40236017/mcafee-mysql-audit-plugin-version-vs-mysql-version

**Comment by zafermalik** [comment]
Hi Aharon,

Thanks for updating latest plugin for 5.6 and it is working fine.

Thanks a lot.

**Comment by aharonrobbins** [comment]
Thanks for letting me know; glad it's working. Closing the issue.
