### ISSUE TITLE
Mysql crash after restart

### ISSUE THREAD

**Issue by liupenny** [mcafee/mysql-audit#151]
Version
=============
System:Ubuntu14.04 Desktop  
Mysql:mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3(sudo apt-get install mysql-server)  
Mysql-plugin:audit-plugin-mysql-5.5-1.1.0-641-linux-x86_64.zip  

Problem
=============
mysql-plugin will only be effective after the installation. After that, no matter what i changed in my.cnf . Sometimes 'sudo service mysql restart' succeed , sometimes it failed and return 'stop: Unknown instance: 
mysql start/running, process 49751 ' . At this time , if i 'mysql -u root -p' ,it returned 'ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111) '

Installion
=============
apt-get install mysql  
cp the libaudit_plugin.so to /usr/lib/mysql/plugin  
change the [mysqld] in my.cnf as below(Primary cnf)
mysql -u root -p  (since writting 'plugin-load=AUDIT=libaudit_plugin.so' to the my.cnf doesn't work)
INSTALL PLUGIN AUDIT SONAME 'libaudit_plugin.so'; 
it will succeed and i can see the audit.log

My.cnf
=============
## Primary cnf

[mysqld]  
user		= mysql  
pid-file	= /var/run/mysqld/mysqld.pid  
socket		= /var/run/mysqld/mysqld.sock  
port		= 3306  
basedir		= /usr  
datadir		= /var/lib/mysql  
tmpdir		= /tmp  
lc-messages-dir	= /usr/share/mysql  

audit_json_file=ON  
audit_json_log_file=/var/log/mysql/audit.log    
audit_validate_checksum=OFF  

skip-external-locking  
bind-address		= 127.0.0.1  
key_buffer		= 16M  
max_allowed_packet	= 16M  
thread_stack		= 192K  
thread_cache_size       = 8  
myisam-recover         = BACKUP  
query_cache_limit	= 1M  
query_cache_size        = 16M  
log_error = /var/log/mysql/error.log  
expire_logs_days	= 10  
max_binlog_size         = 100M  

## After change

[mysqld]  
user		= mysql  
pid-file	= /var/run/mysqld/mysqld.pid  
socket		= /var/run/mysqld/mysqld.sock  
port		= 3306  
basedir		= /usr  
datadir		= /var/lib/mysql  
tmpdir		= /tmp  
lc-messages-dir	= /usr/share/mysql  
  
audit_json_file=ON  
audit_json_log_file=/var/log/mysql/audit.log    
audit_validate_checksum=OFF  
audit_whitelist_cmds=select,insert  

skip-external-locking  
bind-address		= 127.0.0.1  
key_buffer		= 16M  
max_allowed_packet	= 16M  
thread_stack		= 192K  
thread_cache_size       = 8  
myisam-recover         = BACKUP  
query_cache_limit	= 1M  
query_cache_size        = 16M  
log_error = /var/log/mysql/error.log  
expire_logs_days	= 10  
max_binlog_size         = 100M  

Mysql error.log
=============

161126 23:00:41 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.  
161126 23:00:41 [Note] Plugin 'FEDERATED' is disabled.  
161126 23:00:41 [Note] Audit Plugin: Set interface version to: 12941568 (50553)  
161126 23:00:41 [Warning] option 'audit-json-file-bufsize': signed value 0 adjusted to 1  
161126 23:00:41 [Warning] option 'plugin-audit-json-file-bufsize': signed value 0 adjusted to 1  
161126 23:00:41 InnoDB: The InnoDB memory heap is disabled  
161126 23:00:41 InnoDB: Mutexes and rw_locks use GCC atomic builtins  
161126 23:00:41 InnoDB: Compressed tables use zlib 1.2.8  
161126 23:00:41 InnoDB: Using Linux native AIO  
161126 23:00:41 InnoDB: Initializing buffer pool, size = 128.0M  
161126 23:00:41 InnoDB: Completed initialization of buffer pool  
161126 23:00:41 InnoDB: highest supported file format is Barracuda.  
161126 23:00:42  InnoDB: Waiting for the background threads to start  
161126 23:00:43 InnoDB: 5.5.53 started; log sequence number 1599047  
161126 23:00:43 [Note] Audit Plugin: starting up. Version: 1.1.0 , Revision: 641 (64bit). AUDIT plugin interface version: 50553 (0xc579). MySQL Server version: 5.5.53-0ubuntu0.14.04.1.  
161126 23:00:43 [Note] Audit Plugin: setup_offsets audit_offsets: (null) validate_checksum: 0 offsets_by_version: 1  
161126 23:00:43 [Note] Audit Plugin: mysqld: /usr/sbin/mysqld (1389d5486360c6d7802244182805d42d)   
161126 23:00:43 [ERROR] Audit Plugin: Offsets: 5.5.53 (d5f027aa107b0947f102b362577e1f5b) match thread validation check fails with value: 0. Skipping offset.  
161126 23:00:43 [Note] Audit Plugin: extended offsets validate res: MySQL thread id 123456, OS thread handle 0x0, query id 789 aud_tusr
161126 23:00:43 [Note] Audit Plugin: Using decrement (24) offsets from offset version: 5.5.53 (d5f027aa107b0947f102b362577e1f5b) values: 6120 6168 3792 4288 88 2592 96 0 32 104  
161126 23:00:43 [Note] Audit Plugin: Set whitelist_cmds num: 2, value: select,insert  
161126 23:00:43 [Note] Audit Plugin: Set password_masking_cmds num: 7, value:   CREATE_USER,GRANT,SET_OPTION,SLAVE_START,CREATE_SERVER,ALTER_SERVER,CHANGE_MASTER  
161126 23:00:43 [Note] Audit Plugin: Compile password_masking_regex  res: [1]  
161126 23:00:43 [Note] Audit Plugin: Set password_masking_regex  value: [identified(?:/\*.*?\*/|\s)*?by(?:/\*.*?\*/|\s)*?(?:password)?(?:/\*.*?\*/|\s)*?['|"](?<psw>.*?)(?<!\\)['|"]|password(?:/\*.*?\*/|\s)*?\((?:/\*.*?\*/|\s)*?['|"](?<psw>.*?)(?<!\\)['|"](?:/\*.*?\*/|\s)*?\)|password(?:/\*.*?\*/|\s)*?(?:for(?:/\*.*?\*/|\s)*?\S+?)?(?:/\*.*?\*/|\s)*?=(?:/\*.*?\*/|\s)*?['|"](?<psw>.*?)(?<!\\)['|"]|password(?:/\*.*?\*/|\s)*?['|"](?<psw>.*?)(?<!\\)['|"]]  
161126 23:00:43 [Note] Audit Plugin: Set json_socket_name str: [] value: [/var/run/db-audit/mysql.audit__var_lib_mysql_3306]  
161126 23:00:43 [Note] Audit Plugin: bufsize for file [/var/log/mysql/audit.log]: 1. Value of json_file_bufsize: 1.  
161126 23:00:43 [Note] Audit Plugin: success opening file: /var/log/mysql/audit.log.  
161126 23:00:43 [Note] Audit Plugin: mem func addr: 0x7fe4e173a000 mem start addr: 0x7fe4e173a000 page size: 4096  
161126 23:00:43 [Note] Audit Plugin: hot patching function: 0x560ad02c89f0, trampolineFunction: 0x7fe4e173a000 trampolinePage: 0x7fe4e173a000  
161126 23:00:43 [Note] Audit Plugin: hot patch for: mysql_execute_command (0x560ad02c89f0) complete. Audit func: 0x7fe4e17398c0, Trampoline address: 0x7fe4e173a000, size: 20, used: 34.  
161126 23:00:43 [Note] Audit Plugin: hot patching function: 0x560ad02c4460, trampolineFunction: 0x7fe4e173a030 trampolinePage: 0x7fe4e173a000  
161126 23:00:43 [ERROR] Audit Plugin: unable to disassemble at address: 0x0x560ad02c4468. Found relative addressing for instruction: [jnz 0x560ad02c4473]. Aborting.  
161126 23:00:43 [ERROR] Audit Plugin: unable to hot patch log_slow_statement (0x560ad02c4460). res: -1.  
161126 23:00:43 [ERROR] Audit Plugin: Failed hot patch. Continuing as non-critical.  
161126 23:00:43 [Note] Audit Plugin: hot patching function: 0x560ad028d320, trampolineFunction: 0x7fe4e173a030 trampolinePage: 0x7fe4e173a000  
161126 23:00:43 [Note] Audit Plugin: hot patch for: acl_authenticate (0x560ad028d320) complete. Audit func: 0x7fe4e1739b40, Trampoline address: 0x7fe4e173a030, size: 14, used: 28.  
161126 23:00:43 [Note] Audit Plugin: hot patching function: 0x560ad029d350, trampolineFunction: 0x7fe4e173a050 trampolinePage: 0x7fe4e173a000  
161126 23:00:43 [Note] Audit Plugin: hot patch for: send_result_to_client (0x560ad029d350) complete. Audit func: 0x7fe4e1739570, Trampoline address: 0x7fe4e173a050, size: 20, used: 34.  
161126 23:00:43 [Note] Audit Plugin: hot patching function: 0x560ad02c51e0, trampolineFunction: 0x7fe4e173a080 trampolinePage: 0x7fe4e173a000  
161126 23:00:43 [Note] Audit Plugin: hot patch for: check_table_access (0x560ad02c51e0) complete. Audit func: 0x7fe4e1739420, Trampoline address: 0x7fe4e173a080, size: 16, used: 30.  
161126 23:00:43 [Note] Audit Plugin: hot patching function: 0x560ad02999e0, trampolineFunction: 0x7fe4e173a0a0 trampolinePage: 0x7fe4e173a000  
161126 23:00:43 [Note] Audit Plugin: hot patch for: open_tables (0x560ad02999e0) complete. Audit func: 0x7fe4e1739640, Trampoline address: 0x7fe4e173a0a0, size: 16, used: 30.  
161126 23:00:43 [Note] Audit Plugin: Done initializing sql command names. status_vars_index: [139], com_status_vars: [0x560ad0c6c820].  
161126 23:00:43 [Note] Audit Plugin: Init completed successfully.  
161126 23:00:43 [Note] Server hostname (bind-address): '127.0.0.1'; port: 3306  
161126 23:00:43 [Note]   - '127.0.0.1' resolves to '127.0.0.1';  
161126 23:00:43 [Note] Server socket created on IP: '127.0.0.1'.  
161126 23:00:43 [Note] Event Scheduler: Loaded 0 events  
161126 23:00:43 [Note] /usr/sbin/mysqld: ready for connections.  
Version: '5.5.53-0ubuntu0.14.04.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Ubuntu)  
07:00:44 UTC - mysqld got signal 11 ;  
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed, 
something is definitely wrong and this may fail.

key_buffer_size=16777216  
read_buffer_size=131072  
max_used_connections=1  
max_threads=151  
thread_count=1  
connection_count=1  
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 346701 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.  

Thread pointer: 0x560ad313e690  
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...  
stack_bottom = 7fe4dc074e98 thread_stack 0x30000  
/usr/sbin/mysqld(my_print_stacktrace+0x20)[0x560ad04c5b60]  
/usr/sbin/mysqld(handle_fatal_signal+0x3d5)[0x560ad03aeea5]  
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7fe4e0a47330]  
/usr/sbin/mysqld(_Z21mysql_execute_commandP3THD+0x89)[0x560ad02c8a79]  
/usr/lib/mysql/plugin/libaudit_plugin.so(+0xc97b)[0x7fe4e173997b]  
/usr/sbin/mysqld(_Z11mysql_parseP3THDPcjP12Parser_state+0x160)[0x560ad02cf720]  
/usr/sbin/mysqld(_Z16dispatch_command19enum_server_commandP3THDPcj+0x1df2)[0x560ad02d1cb2]  
/usr/sbin/mysqld(_Z24do_handle_one_connectionP3THD+0x176)[0x560ad035ee96]  
/usr/sbin/mysqld(handle_one_connection+0x41)[0x560ad035eef1]  
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8184)[0x7fe4e0a3f184]  
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fe4e016237d]  

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (7fe4c40056a0): is an invalid pointer
Connection ID (thread ID): 2
Status: NOT_KILLED

The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.

restart mysql
=============
after changing the my.cnf, to execute "sudo service mysql restart" , it will return  
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)

**Comment by aharonrobbins** [comment]
Thanks for the report. We will try to investigate.


Aharon Robbins
Software Engineer
Database Security
Intel Security


2 HaNagar Street
Kfar Saba 44425
ISRAEL

Direct: +972 2 589 2545
Mobile: +972 54 788 6586
Web: www.mcafee.com<http://www.intelsecurity.com/>

The information contained in this email message may be privileged, confidential and protected from disclosure. If you are not the intended recipient, any review, dissemination, distribution or copying is strictly prohibited. If you have received this email message in error, please notify the sender by reply email and delete the message and any attachments.

**Comment by liupenny** [comment]
can anyone tell me which version of mysql and mysql-audit are the most stable?  urgent

**Comment by aharonrobbins** [comment]
The current released plugin should be the most stable.

You can try the release of MySQL from mysql.org instead of the one compiled by Debian.  You may wish to move to the latest version of MySQL 5.7, which will have the most features.

Hope this helps,

Aharon


Aharon Robbins
Software Engineer
Database Security
Intel Security


2 HaNagar Street
Kfar Saba 44425
ISRAEL

Direct: +972 2 589 2545
Mobile: +972 54 788 6586
Web: www.mcafee.com<http://www.intelsecurity.com/>

The information contained in this email message may be privileged, confidential and protected from disclosure. If you are not the intended recipient, any review, dissemination, distribution or copying is strictly prohibited. If you have received this email message in error, please notify the sender by reply email and delete the message and any attachments.

**Comment by liupenny** [comment]
I have tried it with mysql5.7 from mysql.org but it return the same error

**Comment by aharonrobbins** [comment]
Thanks for the update.  We will investigate. You might try using the previous release of the plugin and see if that works any better.


Aharon Robbins
Software Engineer
Database Security
Intel Security


2 HaNagar Street
Kfar Saba 44425
ISRAEL

Direct: +972 2 589 2545
Mobile: +972 54 788 6586
Web: www.mcafee.com<http://www.intelsecurity.com/>

The information contained in this email message may be privileged, confidential and protected from disclosure. If you are not the intended recipient, any review, dissemination, distribution or copying is strictly prohibited. If you have received this email message in error, please notify the sender by reply email and delete the message and any attachments.

**Comment by aharonrobbins** [comment]
Hi. Can you please email us the error log from MySQL 5.7?

Thanks.
