### ISSUE TITLE
Allow to configure audit file creation group

### ISSUE THREAD

**Issue by alledm** [mcafee/mysql-audit#153]
Hello,

Your plugin creates the audit file with permissions:
```-rw-r----- mysql mysql audit.log```

However if I want to use something like logstash to read it, it would force me to add the `logstash` user to the `mysql` group which is clearly not good from a security prospective.

I would like to be able to change the permissions to have a configurable group, which could default to the `adm` group which is the group commonly used by processes that read logs.

**Comment by aharonrobbins** [comment]
Thanks for the suggestion. For MySQL to change the group of the file to something else, you would have to add the mysql user to the desired group.  Is that OK with you?

**Comment by alledm** [comment]
Yes I think so. In that case probably the default should not be `adm` I guess.
Thank you!

**Comment by aharonrobbins** [comment]
You're welcome. We will see if this fits into our roadmap. Thanks for the suggestion.

**Comment by aharonrobbins** [comment]
Some quick research indicates that MySQL does not build up and set a group set of supplementary groups.  This would seem to preclude implementation of this feature.

**Comment by alledm** [comment]
The default could be 'mysql' but the users could then change it providing
the right groups are created and configured?

**Comment by aharonrobbins** [comment]
Users would have to change the group once the file was created, or create it and then change the ownership and group.  But all that would be outside the scope of the code in the plugin itself.

**Comment by guylichtman** [comment]
@alledm, I would suggest checking out the option of directing the plugin to a Unix socket. And then have syslog-ng process the input.

**Comment by aharonrobbins** [comment]
Closing this issue.
