### ISSUE TITLE
v1.1.0 download not available

### ISSUE THREAD

**Issue by jmcnaomh** [mcafee/mysql-audit#154]
https://bintray.com/mcafee/mysql-audit-plugin/release

shows the following:

Downloads (ver: 1.1.0-642)
No direct downloads selected for this package.

I need this version so it can support 5.7.16

**Comment by aharonrobbins** [comment]
Thanks for the report. We will look into this.

**Comment by guylichtman** [comment]
You need to click the "Files" tab. Check the following link:

https://bintray.com/mcafee/mysql-audit-plugin/release/1.1.0-642#files

**Comment by aharonrobbins** [comment]
Note that we just made the 1.1.1 release. Thanks.
