### ISSUE TITLE
Change password using update query logs password in cleartext

### ISSUE THREAD

**Issue by rajamadhavan** [mcafee/mysql-audit#158]
While using audit plugin, I noticed that the password is getting logged in cleartext when using UPDATE command. The same is hidden when using SET PASSWORD and also during CREATE USER.

Audit Plugin Version: audit-plugin-mysql-5.6-1.1.1-660 (CentOS 6.8)
MySQL server version :  5.6.35

SET and CREATE commands

`{"msg-type":"activity","date":"1485761924460","thread-id":"4","query-id":"109","user":"root","priv_user":"root","ip":"","host":"localhost","connect_attrs":{"_os":"Linux","_client_name":"libmysql","_pid":"16270","_client_version":"5.6.35","_platform":"x86_64","program_name":"mysql"},"cmd":"set_option","query":"SET PASSWORD FOR 'donald'@'localhost' = PASSWORD('***')"}`
`{"msg-type":"activity","date":"1485763977038","thread-id":"4","query-id":"112","user":"root","priv_user":"root","ip":"","host":"localhost","connect_attrs":{"_os":"Linux","_client_name":"libmysql","_pid":"16270","_client_version":"5.6.35","_platform":"x86_64","program_name":"mysql"},"cmd":"create_user","query":"CREATE USER 'roger'@'localhost' IDENTIFIED BY '***'"}`

Password logged in cleartext with UPDATE.

`{"msg-type":"activity","date":"1485763882908","thread-id":"4","query-id":"111","user":"root","priv_user":"root","ip":"","host":"localhost","connect_attrs":{"_os":"Linux","_client_name":"libmysql","_pid":"16270","_client_version":"5.6.35","_platform":"x86_64","program_name":"mysql"},"cmd":"update","objects":[{"db":"mysql","name":"user","obj_type":"TABLE"}],"query":"UPDATE mysql.user SET Password=PASSWORD('abcd@123') WHERE USER='donald' AND Host='localhost'"}`

Thanks
-Raja

**Comment by aharonrobbins** [comment]
Thanks for the report. We will work to get this fixed in our next release.

**Comment by aharonrobbins** [comment]
Hi. As a workaround, you should be able to put

audit_password_masking_cmds="CREATE_USER,GRANT,SET_OPTION,SLAVE_START,CREATE_SERVER,ALTER_SERVER,CHANGE_MASTER,UPDATE"

in your /etc/my.cnf. This adds 'update' to the list of commands that will be searched for a password.

We will revise the source for our next release.

**Comment by rajamadhavan** [comment]
Yes. I just tried that. Works. Thanks.

-Raja

**Comment by aharonrobbins** [comment]
OK, great!

**Comment by aharonrobbins** [comment]
We have just released a new dev snapshot that now includes UPDATE. I am closing this issue. Thanks!
