### ISSUE TITLE
I want to use Mcafee Audit Plugin on Percona-Server-server-57-5.7.15.

### ISSUE THREAD

**Issue by 529** [mcafee/mysql-audit#162]
I want to use Mcafee Audit Plugin on Percona-Server-server-57-5.7.15.
I cannot use it...

I checked below url.
https://github.com/mcafee/mysql-audit/wiki/Changelog

v1.1.0 or more is required.

But binary file cannot download below url yet. 
https://bintray.com/mcafee/mysql-audit-plugin/release

So I tried to compile and make binary file.
According to the compiling.txt (https://github.com/mcafee/mysql-audit/blob/master/compiling.txt)

===
mysql-5.7.17 download from dev.mysql.com

v1.1.1 download from mcafee git repository
$ wget https://github.com/mcafee/mysql-audit/archive/v1.1.1.tar.gz

$ tar xvzf mysql-5.7.17.tar.gz
$ tar xvzf v1.1.1.tar.gz
$ wget http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz
$ tar xvzf boost_1_59_0.tar.gz

$ cd /path/to/mysql-5.7.17
$ cmake -DWITH_BOOST=/path/to/boost_1_59_0 .
$ make

$ pwd
/path/to/mysql-audit-1.1.1
$ chmod +x bootstrap.sh
$  ./bootstrap.sh
$ CXX='gcc -static-libgcc' CC='gcc -static-libgcc' ./configure --with-mysql=../mysql-5.7.17 --with-mysql-libservices=../mysql-5.7.17/libservices/libmysqlservices.a
$ make

// get offset

$ wget https://github.com/mcafee/mysql-audit/archive/v1.1.1.tar.gz

$ tar xvzf v1.1.1.tar.gz
-bash-4.1$ pwd
/path/to/mysql-audit-1.1.1/offset-extract
-bash-4.1$ chmod +x offset-extract.sh

$ /path/to/mysql-audit-1.1.1/offset-extract/offset-extract.sh /path/to/Percona-Server-5.7.15-9-Linux.x86_64.ssl101/bin/mysqld
//offsets for: /path/to/Percona-Server-5.7.15-9-Linux.x86_64.ssl101/bin/mysqld (5.7.15-9)
{"5.7.15-9","5efa1d884bcd6361ed3067e383518300", 8224, 8288, 3864, 5016, 456, 360, 0, 32, 64, 160, 536, 8420, 4592, 3648, 3656, 3660},
$

$ sudo vim /etc/mysql/my.cnf
...
##-------------------------------------------
## McAfee AUDIT
##-------------------------------------------
!include /etc/mysql/_include/mcafee_audit.cnf
plugin-load-add=libaudit_plugin.so
audit_json_file = ON
audit_json_log_file=/path/to/instance/logs/mysqld-audit.json

$ sudo vim /etc/mysql/_include/mcafee_audit_5.7.15.cnf
loose-audit_offsets=8224, 8288, 3864, 5016, 456, 360, 0, 32, 64, 160, 536, 8420, 4592, 3648, 3656, 3660

mysql> show plugins;
| AUDIT                       | ACTIVE   | AUDIT              | libaudit_plugin.so | GPL     |

It seems to move without problems.
But expected version is not working, and Audit log is not output...

mysql> show status like 'audit%';
+------------------------+-------------+
| Variable_name          | Value       |
+------------------------+-------------+
| Audit_protocol_version | 1.0         |
| Audit_version          | 1.0.0-99999 |
+------------------------+-------------+
2 rows in set (0.00 sec)

ls /path/to/instance/logs/mysqld-audit.json
ls: cannot access /path/to/instance/logs/mysqld-audit.json: No such file or directory

===

I have questions.
1. Is the procedure incorrect?
2. When is v1.1.1 binary file uploaded to jfrog?

regards

**Comment by guylichtman** [comment]
Binary files for 1.1.1 are available on bintray. 

See: https://bintray.com/mcafee/mysql-audit-plugin/release/1.1.1-660#files

**Comment by 529** [comment]
Excuse me. I was overlooking.
I was able to use it.

Thank you for your help.

regartds
