### ISSUE TITLE
Documentation improvement: describe audit.json date field format

### ISSUE THREAD

**Issue by selivan** [mcafee/mysql-audit#169]
I didn't find it in documentation and had to search plugin and mysql sources to find that it's unix timestamp in milliseconds. I think it is worth mentioning somewhere in wiki. Wiki is read-only, so I can't propose a PR.

**Comment by aharonrobbins** [comment]
Thanks. I'll update the Wiki.

**Comment by aharonrobbins** [comment]
Added [[Miscellaneous Notes]] section to the wiki. Thanks!

**Comment by selivan** [comment]
It may be also nice to mention on that wiki page that Unix timestamp is always in UTC, not local system time. It's probably the thing that good sysadmin should know already, but I forgot at first, shame on me :(

**Comment by aharonrobbins** [comment]
OK. Done. Thanks.
