### ISSUE TITLE
Bug / Security risk: Users can be unintentionally whitelisted.

### ISSUE THREAD

**Issue by yetanotherdba** [mcafee/mysql-audit#172]
#### Issue 
- When matching usernames, there is a risk of unintentionally whitelisting users which names contains the substring of the whitelisted user as a prefix.

#### Steps to reproduce
- Install audit plugin and enable logging to json file. 
- Whitelist `testuser`
- Attempt to connect / issue queries as `testuser`
  - These will be whitelisted as expected
- Attempt to connect / issue queries as `testuse`
  - These will be audited as expected
- Attempt to connect / issue queries as `testuser123`
  - These will be whitelisted and thus not audited, even though this username is not whitelisted.

#### Test Environment
- MySQL 5.7.19
- audit plugin 1.1.4, 1.1.5 and straight from master.
- x86_64 running CentOS 7

**Comment by aharonrobbins** [comment]
Thanks for the note. We'll investigate and fix.

**Comment by aharonrobbins** [comment]
Hi.  Attached is a diff that fixes the problem in my testing.  If you can apply and build the plugin to test, I'd appreciate it.  In the meantime, I will start this through our QA process also.  Thanks!
[whitelist-fix.diff.txt](https://github.com/mcafee/mysql-audit/files/1239097/whitelist-fix.diff.txt)

**Comment by aharonrobbins** [comment]
Oops.  Please ignore the patch for audit_offsets.cc.  Thanks.

**Comment by aharonrobbins** [comment]
I have just pushed new code which includes a fix for this issue.  Binaries have been uploaded to bintray.com.  Closing the issue.  Enjoy.
