### ISSUE TITLE
Can't use boost libraries to enhance audit to mongodb...

### ISSUE THREAD

**Issue by wowmui** [mcafee/mysql-audit#178]
Hello everyone.
When I add some function to curl post or directly insert to mongodb the audit texts with boost::asio and modified src/Makefile.am 
`libaudit_plugin_la_LIBADD += /home/mysql/boost_1_65_0/stage/lib/libboost_*.a`
or 
`AM_CPPFLAGS += /home/mysql/boost_1_65_0 `
and
`libaudit_plugin_la_LIBADD += -lboost_system -lboost_thread`
with modified audit_handler.h
include those thing
```
#undef max
#undef min
#undef test

#include <iostream>
#include <istream>
#include <ostream>
#include <string>
#include <boost/asio.hpp>
#include <boost/thread/thread.hpp>
```
make with no error , but when I use it with mysql 
comming some undefined symbol errors:
```
2017-09-18 12:49:35 42650 [ERROR] Can't open shared library '/usr/local/mysql/lib/plugin/libaudit_plugin.so' (errno: 0 /usr/local/mysql/lib/plugin/libaudit_plugin.so: undefined symbol: _ZN5boost4asio6detail12service_baseINS0_21stream_socket_servic)
2017-09-18 12:49:35 42650 [ERROR] Couldn't load plugin named 'AUDIT' with soname 'libaudit_plugin.so'.
```

I don't truly understand why it can't use with boost libraries . 
I tried Dynamic Link and Static Link , they have same results with those erros.
That made me feel very confused.
thanks for your patience.

**Comment by aharonrobbins** [comment]
Please run the command 'ldd' on the compiled plugin ".so" file and see if any of the libraries it needs are not resolved. In that case, you may need to set the LD_LIBRARY_PATH environment variable to point to the location of the needed library (or libraries) when you invoke mysqld.

**Comment by wowmui** [comment]
@aharonrobbins Hi
I tried ldd them and findout nothing is wrong or can't be found.
```
[root@I plugin]# ldd libaudit_plugin.so.0.0.0 
	linux-vdso.so.1 (0x00007fffafabc000)
	libboost_system.so.1.65.0 => /usr/lib/libboost_system.so.1.65.0 (0x00007fa83f75b000)
	libboost_thread.so.1.65.0 => /usr/lib/libboost_thread.so.1.65.0 (0x00007fa83f535000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007fa83f318000)
	libc.so.6 => /lib/libc.so.6 (0x00007fa83ef62000)
	//lib64/ld-linux-x86-64.so.2 (0x0000003107e00000)
	librt.so.1 => /lib/librt.so.1 (0x00007fa83ed59000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fa83e9c1000)
	libm.so.6 => /lib/libm.so.6 (0x00007fa83e6c5000)
	libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007fa83e4ae000)

[root@I plugin]# ldd /usr/lib/libboost_system.so
	linux-vdso.so.1 (0x00007fff9e9b6000)
	librt.so.1 => /lib/librt.so.1 (0x00007f98b9735000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f98b939d000)
	libm.so.6 => /lib/libm.so.6 (0x00007f98b90a0000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f98b8e8a000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f98b8c6d000)
	libc.so.6 => /lib/libc.so.6 (0x00007f98b88b6000)
	//lib64/ld-linux-x86-64.so.2 (0x0000003107e00000)

[root@I plugin]# ldd /usr/lib/libboost_thread.so
	linux-vdso.so.1 (0x00007fff867fe000)
	libboost_system.so.1.65.0 => /usr/lib/libboost_system.so.1.65.0 (0x00007f1e975e5000)
	librt.so.1 => /lib/librt.so.1 (0x00007f1e973dd000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f1e97044000)
	libm.so.6 => /lib/libm.so.6 (0x00007f1e96d48000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f1e96b32000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f1e96914000)
	libc.so.6 => /lib/libc.so.6 (0x00007f1e9655e000)
	//lib64/ld-linux-x86-64.so.2 (0x0000003107e00000)
```

But unfortunately,still can't open shared library with undefined symbol error.

When I try to move libboost_*.so to another directory and error messages change to:
```
2017-09-19 09:02:56 14759 [ERROR] Can't open shared library '/usr/local/mysql/lib/plugin/libaudit_plugin.so' (errno: 0 libboost_system.so.1.65.0: cannot open shared object file: No such file or directory)
2017-09-19 09:02:56 14759 [ERROR] Couldn't load plugin named 'AUDIT' with soname 'libaudit_plugin.so'.

[root@I plugin]# ldd libaudit_plugin.so.0.0.0 
	linux-vdso.so.1 (0x00007fff049b0000)
	libboost_system.so.1.65.0 => not found
	libboost_thread.so.1.65.0 => not found
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f3ff395f000)
	libc.so.6 => /lib/libc.so.6 (0x00007f3ff35a9000)
	//lib64/ld-linux-x86-64.so.2 (0x0000003107e00000
```

I think this is not because the libaudit_plugin.so can't find boost libraries cause this issue . To confirm this,by creating a stand-alone application with boost and same functions . It can running perfectly and have no undefined symbol errors.
Maybe some deeper places need modify?
Thank you again.

**Comment by aharonrobbins** [comment]
Can you use 'nm' on the various boost libraries to see which one holds _ZN5boost4asio6detail12service_baseINS0_21stream_socket_servic ?  You may be missing a -lboost_asio or some such additional library to be loaded.  Just a thought.

**Comment by wowmui** [comment]
nm every /usr/lib/libbost_*.so and find no one can greped "_ZN5boost4asio6detail12service_baseINS0_21stream_socket_servic" .
But I can find it in my stand-alone application 
```
[root@zz-master-007 mysql-audit]# nm /usr/lib/libboost_*.so | grep _ZN5boost4asio6detail12service_baseINS0_21stream_socket_servic
[root@zz-master-007 mysql-audit]# nothing here... :(
[root@I mysql-audit]# nm /home/mysql/curl_boost/curl_post | grep _ZN5boost4asio6detail12service_baseINS0_21stream_socket_servic
0000000000623b61 u _ZN5boost4asio6detail12service_baseINS0_21stream_socket_serviceINS0_2ip3tcpEEEE2idE
0000000000415ed0 W _ZN5boost4asio6detail12service_baseINS0_21stream_socket_serviceINS0_2ip3tcpEEEEC1ERNS0_10io_serviceE
0000000000415ed0 W _ZN5boost4asio6detail12service_baseINS0_21stream_socket_serviceINS0_2ip3tcpEEEEC2ERNS0_10io_serviceE
0000000000415736 W _ZN5boost4asio6detail12service_baseINS0_21stream_socket_serviceINS0_2ip3tcpEEEED0Ev
000000000041570e W _ZN5boost4asio6detail12service_baseINS0_21stream_socket_serviceINS0_2ip3tcpEEEED1Ev
000000000041570e W _ZN5boost4asio6detail12service_baseINS0_21stream_socket_serviceINS0_2ip3tcpEEEED2Ev
```
And there is no such thing in libboost*.so like libboost_asio...
```
[root@I mysql-audit]# ls /usr/lib/libboost_*.so
/usr/lib/libboost_atomic.so     /usr/lib/libboost_fiber.so       /usr/lib/libboost_log_setup.so  /usr/lib/libboost_math_tr1l.so         /usr/lib/libboost_serialization.so         /usr/lib/libboost_thread.so
/usr/lib/libboost_chrono.so     /usr/lib/libboost_filesystem.so  /usr/lib/libboost_math_c99.so   /usr/lib/libboost_prg_exec_monitor.so  /usr/lib/libboost_signals.so               /usr/lib/libboost_timer.so
/usr/lib/libboost_container.so  /usr/lib/libboost_graph.so       /usr/lib/libboost_math_c99f.so  /usr/lib/libboost_program_options.so   /usr/lib/libboost_stacktrace_addr2line.so  /usr/lib/libboost_type_erasure.so
/usr/lib/libboost_context.so    /usr/lib/libboost_iostreams.so   /usr/lib/libboost_math_c99l.so  /usr/lib/libboost_python.so            /usr/lib/libboost_stacktrace_basic.so      /usr/lib/libboost_unit_test_framework.so
/usr/lib/libboost_coroutine.so  /usr/lib/libboost_locale.so      /usr/lib/libboost_math_tr1.so   /usr/lib/libboost_random.so            /usr/lib/libboost_stacktrace_noop.so       /usr/lib/libboost_wave.so
/usr/lib/libboost_date_time.so  /usr/lib/libboost_log.so         /usr/lib/libboost_math_tr1f.so  /usr/lib/libboost_regex.so             /usr/lib/libboost_system.so                /usr/lib/libboost_wserialization.so
```

Where did she go... and why I can use it in my little app but can't use it in auditplugin....
tried to add -lboost* and nothing changed... X_X
OMG...

**Comment by aharonrobbins** [comment]
So that means the routine is only in one of the static libraries (.a files).  You can try to figure out which .o file  in which .a file has the routine and then manually link that into the plugin.

I am wondering if you could perhaps just reorganize the problem to make it easier to solve. It sounds like you want the plugin to send each JSON record to MongoDB.  I suggest that instead of coupling things so tightly, you simply leave the plugin alone, as follows:

- Configure the plugin to write to a Unix Domain socket, with a location of your choice.
- Write a small standalone application that creates the Unix Domain socket and reads complete lines from the plugin.
- Have the small application do the logging to MongoDB

Does that make any sense?  Hope this helps.

**Comment by wowmui** [comment]
Good idea. But how to configure the plugin to write to a Unix Domain socket instead of file?
Thank you a lot.

**Comment by aharonrobbins** [comment]
Please see configuration section of the wiki. There are configuration variables to enable writing to a socket and to set the name of the socket's path.  If you do that, disable writing to a file - they are two independent  actions.

**Comment by wowmui** [comment]
Wow! Unbelievable ooptions! Sorry for my careless. I thought it was to configure through the socket connect to mysql...

**Comment by aharonrobbins** [comment]
Glad to help. It looks like you are in good shape, so I will close this issue.

**Comment by wowmui** [comment]
@aharonrobbins Love you.
