### ISSUE TITLE
undefined symbol: thd_alloc_service

### ISSUE THREAD

**Issue by 1044730317** [mcafee/mysql-audit#182]
I installed plugins on version 5.7.18 .

        INSTALL PLUGIN AUDIT SONAME 'libaudit_plugin.so';

The following error occurs:
(errno: 13 mysql_5.7.18/lib/plugin/libaudit_plugin.so: undefined symbol: thd_alloc_service)

Find the definition of the error in this file. " mysql-audit-master/src/MySQLPlugin.map  "

{
        global:
                _mysql_plugin_declarations_;
                _mysql_plugin_interface_version_;
                _mysql_sizeof_struct_st_plugin_;
                audit_plugin_so_init;
                thd_alloc_service;

        local: *;
};

What is the effect of this definition?    " thd_alloc_service; "

**Comment by aharonrobbins** [comment]
Hi. Apologies for the late response.  There was a snafu with my email address and I did not see this issue.

Please try the latest version of the plugin. It should support 5.7.18 out of the box.

Thanks!
