### ISSUE TITLE
Mysql Audit Alerts

### ISSUE THREAD

**Issue by Jamalc0m** [mcafee/mysql-audit#183]
Hello,

How I can configure mysql_audit to send alerts to the emails ?

Thanks.

**Comment by aharonrobbins** [comment]
Hi. I am sorry for the late reply. I did not get an email about this issue. :-(

The plugin does not currently support sending alerts to emails.  You would have to change the source to do this.

Also, it's not really designed to work this way. Instead, it logs statements as they're executed either to a file or a Unix domain socket; getting one email per statement would probably flood the mailbox and not be really usable.

Hope this helps.
