### ISSUE TITLE
can i use this mysql-audit in windows?

### ISSUE THREAD

**Issue by jackyrong** [mcafee/mysql-audit#184]
cause i have customers who use mysql 5.7 in windows!

**Comment by aharonrobbins** [comment]
Hi. Sorry for the late response; I'm not sure why I didn't see this.

The MySQL plugin is supported only on Linux.  It would have to be ported to Windows. Doing so would require a way to extract offsets from the Windows version of MySQL, and also some way to perform hot patching of the code. There are other parts of the plugin that assume that the underlying OS is Linux.

All of the above is probably doable, but we do not currently have plans to support the plugin on Windows.  Thanks.
