### ISSUE TITLE
Offsets for Mysql 5.5.59

### ISSUE THREAD

**Issue by atze234** [mcafee/mysql-audit#186]
Hi,
offsets for mysql 5.5.59 are still missing. 
Would be really nice if you can provide them.

180122 10:41:21 [Note] McAfee Audit Plugin: starting up. Version: 1.1.5 , Revision: 774 (64bit). MySQL AUDIT plugin interface version: 50559 (0xc57f). MySQL Server version: 5.5.59-0+deb8u1-log.
180122 10:41:21 [Note] McAfee Audit Plugin: setup_offsets audit_offsets: (null) validate_checksum: 1 offsets_by_version: 1
180122 10:41:21 [Note] McAfee Audit Plugin: mysqld: /usr/sbin/mysqld (6eb25d71aee1afdcb5760daf622a76b0)
180122 10:41:21 [Note] McAfee Audit Plugin: Couldn't find proper THD offsets for: 5.5.59-0+deb8u1-log

Thank you
Jörg

**Comment by atze234** [comment]
I've extracted them on Debian Jessie, and they're working with latest Debian Jessie Package:
//offsets for: /mnt/mysqlbuild/2/mysql-5.5-5.5.59/builddir/sql/mysqld (5.5.59-0)
{"5.5.59-0","0399a78b76129a2774e3c30024c3e1a4", 6120, 6168, 3792, 4288, 88, 2592, 96, 0, 32, 104, 120, 6240, 4168, 0, 0, 0, 496, 0, 0, 5984, 6008, 5992, 6048, 548, 516},

**Comment by aharonrobbins** [comment]
Thanks for the note. We will push a new dev snapshot today or tomorrow, I hope.

**Comment by aharonrobbins** [comment]
Hi. We have pushed source code updates and uploaded new binaries. Please let us know if they're working for you. Thanks.
