### ISSUE TITLE
Failed to to install mysql audit

### ISSUE THREAD

**Issue by testerrrrrr** [mcafee/mysql-audit#188]
When I try to execute the file, it gives me the following error:

stg03@ubuntu:~/mysql-audit$ sudo ./configure --with-mysql=5.7.20
[sudo] password for stg03: 
Sorry, try again.
[sudo] password for stg03: 
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable debugging... no
checking for mysql source code... configure: error: Failed to find required header file include/my_dir.h in 5.7.20, check the path and make sure you've run './configure ..<options>.. && cd include && make' in MySQL 5.1 sources dir or 'cmake . && make' in MySQL 5.5 sources dir.

Can anyone help what could be the issue ?

Thanks,

**Comment by testerrrrrr** [comment]
@aharonrobbins

**Comment by aharonrobbins** [comment]
Hi. Please see the file compiling.txt in the distribution. Did you follow the instructions there?

Thanks,

Aharon

**Comment by aharonrobbins** [comment]
Using the instructions in compiling.txt, I was able to compile the bits of 5.7.20 as needed and also the plugin. I used the tarball that comes with the Boost headers.  Hope this helps.
