### ISSUE TITLE
ERROR 1123 (HY000): Can't initialize function 'AUDIT'; Plugin initialization function failed

### ISSUE THREAD

**Issue by bjayac** [mcafee/mysql-audit#189]
Hii

Iam getting below error while enabiling MYSQL paudit plugin.

Please help me .

mysql>  SHOW VARIABLES LIKE 'version';
+---------------+------------------------------+
| Variable_name | Value                        |
+---------------+------------------------------+
| version       | 5.7.21-ndb-7.5.9-cluster-gpl |
+---------------+------------------------------+
1 row in set (0.00 sec)

mysql> INSTALL PLUGIN AUDIT SONAME 'libaudit_plugin.so';
ERROR 1123 (HY000): Can't initialize function 'AUDIT'; Plugin initialization function failed.
mysql> install plugin MCAFEE soname 'libaudit_plugin.so';
ERROR 1127 (HY000): Can't find symbol 'MCAFEE' in library
mysql>

Path: /apps/mysql/7.5.9/lib/plugin

[root@SQLNode utils]# ./offset-extract.sh /apps/mysql/7.5.9/bin/mysqld
//offsets for: /apps/mysql/7.5.9/bin/mysqld (5.7.21-ndb-7.5.9-cluster-gpl)
{"5.7.21-ndb-7.5.9-cluster-gpl","ffa351f8e8303d36cb13db74ea9b298a", 7816, 7864, 3632, 4784, 456, 360, 0, 32, 64, 160, 536, 7980, 4360, 3648, 3656, 3660, 6064, 2072, 8, 7048, 7088, 7072, 13448, 148, 672},
[root@SQLNode utils]# pwd
/apps/mysql/7.5.9/lib/plugin/audit-plugin-mysql-5.7-1.1.6-784/utils
[root@SQLNode utils]#

Also below is the error.

[ERROR] McAfee Audit Plugin: Offsets: 5.7.21 (3c33f208ec4d6345d15d048cf48a6f49) match thread validation check fails with value: 0. Skipping offset.

**Comment by aharonrobbins** [comment]
Hi. It looks like you need to put the offsets you've extracted into the /etc/my.cnf file, as described in the "Offset Extraction" section in the "Troubleshooting" page in the wiki.  All you need is the comma-separated list of numbers, and not the first two strings or the enclosing braces.

I hope this helps.

**Comment by bjayac** [comment]
Thanks
