### ISSUE TITLE
Question: Is there a way to audit queries coming from a specific channel only?

### ISSUE THREAD

**Issue by akashsinha** [mcafee/mysql-audit#19]
I have a web application running with jdbc connector.  I want to audit the queries coming from mysql console and discard the one coming from web apps. (Suppose the user/host is common in both the cases)

Is there any configuration using which i could achieve the above?

**Comment by guylichtman** [comment]
We've added in version 1.1.1 new logging options: `audit_client_capabilities` and `audit_sess_connect_attrs`. `audit_client_capabilities` will enable logging of the client_capabilities value (it is disabled by default). `audit_sess_connect_attrs` adds very useful info about client connection attributes but will only work with MySQL 5.6 and up (client also required to be 5.6 and up). See the configuration page in the wiki for further info: https://github.com/mcafee/mysql-audit/wiki/Configuration.
