### ISSUE TITLE
mysql mcafee audit plugin version and MySQL version

### ISSUE THREAD

**Issue by liavs** [mcafee/mysql-audit#193]
Hi 

I could not find the info which 'mcafee audit plugin' file fits which MySQL minor version?
I saw there are plugin files for 5.6 and file for 5.7.
But I did not find a file stating which MySQL MINOR version this plugin fits.
for example which plugin file fits MySQL 5.7.21 ?

Thanks

**Comment by horovitzdan** [comment]
Latest release support 5.7.21

**Comment by liavs** [comment]
Thanks Dan :-)

But how do I know , for example, what is the latest MySQL minor version supported by:
 "audit-plugin-mysql-5.7-1.1.4-**707**-linux-x86_64.zip" file ?
Is there a place it is documented in ?

**Comment by horovitzdan** [comment]
Although it should be, there isn't one right now. I'll explicitly ask to update any new DB version support in the release notes.

**Comment by liavs** [comment]
Thanks again Dan :-) I really appreciate your swift answers 

So may I assume that the latest mcafee mysql plugin version ALWAYS supports older MySQL versions?
E.G Latest release of mcafee supports 5.7.21 and 5.7.16 ?

**Comment by horovitzdan** [comment]
Yes - you can assume support for the older versions too. Pay attention that we decided to end support for very old versions in one of the latest releases (like MySQL 5.1). Please check the change log too located at for the full picture: 
https://github.com/mcafee/mysql-audit/wiki/Changelog

**Comment by liavs** [comment]
Thanks !  your input was very helpfull
