### ISSUE TITLE
Probably not news: Does not work with MariaDB 5.5.35

### ISSUE THREAD

**Issue by acscott** [mcafee/mysql-audit#73]
Is it possible to get a build that works with MariaDB 5.5?  In MariaDB they replaced the my_getsystime function with my_hrtime_t my_hrtime() in my_getsystime.c.  This provides a high resolution time structure.

When installing the plugin with install plugin audit soname 'libaudit_plugin.so"

it returns:

ERROR 1126 (HY000): Can't open shared library '/usr/lib64/mysql/plugin/libaudit_plugin.so' (errno: 2, undefined symbol: my_getsystime)

OS: CentOS-6.4-x86_64
DB version: MariaDB 5.5.35
Audit Plugin: mysql-5.5-1.0.4-459-linux-x86_64.zip

**Comment by DefenceLogic** [comment]
Please can you tell me if there is a binary release that supports MariaDB 5.5.6 on Centos 7 as the last update was from 2014.
