### ISSUE TITLE
Question: Is there anyway to output any sql cmd success/failure execution status?

### ISSUE THREAD

**Issue by yo2** [mcafee/mysql-audit#82]
Hi,

The mysql-audit.json logged sql cmd such as create / drop, etc. But for auditing, it will be useful to record a succesful or failure execution status. For example to find out if there is any failure attempt to modify the database/data.
Is there anyway to output any sql cmd success/failure execution status into the mysql-audit.json? 

regards
Yo.

**Comment by aharonrobbins** [comment]
Logging of success / failure status (a numeric code) is now included in the plugin.  Much thanks.
