### ISSUE TITLE
any query show "Query OK, 0 rows affected (0.00 sec)"

### ISSUE THREAD

**Issue by pengzi** [mcafee/mysql-audit#98]
when running a query sql on a mysql clinet,  if you execute "ctrl+c"  and then execute any sql you will got "Query OK, 0 rows affected (0.00 sec)".

like this:
 select * from table1 limit 1000;
when the screen show the reuslt, execute "ctrl+c"

show tables;
Query OK, 0 rows affected (0.00 sec)

select now();
Query OK, 0 rows affected (0.00 sec)

select version();
Query OK, 0 rows affected (0.00 sec)

select 1+2;
Query OK, 0 rows affected (0.01 sec)

this is a bug or configuration problem？

**Comment by pengzi** [comment]
with out plugin ,if you execute "ctrl+c" and then execute any sql you will got "ERROR 1317(70100): Query execution was interrupted".

**Comment by guylichtman** [comment]
Thanks for reporting this. What is the MySQL version you are testing on?

**Comment by pengzi** [comment]
Percona Server 5.5.21 and 5.5.35

**Comment by pengzi** [comment]
can you repeat it?




lzp888127@hotmail.com

From: Guy Lichtman
Date: 2015-01-19 15:56
To: mcafee/mysql-audit
CC: pengzi
Subject: Re: [mysql-audit] any query show "Query OK, 0 rows affected (0.00 sec)" (#98)
Thanks for reporting this. What is the MySQL version you are testing on?

**Comment by guylichtman** [comment]
I am not able to see this same behavior, although I didn't test with the exact versions you are using. You can send out the mysql error log. Would like to see if there are any errors there.

**Comment by pengzi** [comment]
mysql didn't have any errors on that time. I had set audit_json_file=off ,this problem still, but after uninstall it's OK

**Comment by guylichtman** [comment]
I can confirm that this is a bug which is happening with mysql 5.5.x. Will be pushing a commit soon to resolve the issue.

**Comment by guylichtman** [comment]
Fix has been committed. You can use the latest dev snapshot build available at: https://bintray.com/mcafee/mysql-audit-plugin/dev-snapshot/view . Note that new offsets have been added specifically for Percona. I recommend running again the offset-extract.sh script (latest version) as described here: https://github.com/mcafee/mysql-audit/wiki/Troubleshooting#offset-extraction .

**Comment by pengzi** [comment]
Ok , thanks.
