### ISSUE TITLE
How to install audit plugin for multiple running mysql instances on a single server

### ISSUE THREAD

**Issue by vishal08jan** [mcafee/mysql-audit#99]
Hi

I have a server where 1 mysql 5.5.server is running and there are 2 instances of mysql 5.6 running.
5.5 - RPM installation
5.6 - Binary Installation
I already have audit plugin installed for mysql 5.5 but have issues installing audit plugin on mysql 5.6.

I am getting the following error

mysql> INSTALL PLUGIN AUDIT SONAME 'libaudit_plugin.so';
ERROR 1123 (HY000): Can't initialize function 'AUDIT'; Plugin initialization function failed.

**Comment by mysqlboy** [comment]
Are you seeing errors in your mysql error log? Are you using a 5.6
compatible version of the audit plugin?

**Comment by vishal08jan** [comment]
Hi 

yes the plugin is 5.6 compatible.Errors from Error log:

2015-01-29 16:49:48 64349 [Note] Audit Plugin: starting up. Version: 1.0.6 , Revision: 491 (64bit). AUDIT plugin interface version: 769 (0x301). MySQL Server version: 5.6.22-log.
2015-01-29 16:49:48 64349 [Note] Audit Plugin: setup_offsets audit_offsets: (null) validate_checksum: 1 offsets_by_version: 1
2015-01-29 16:49:49 64349 [Note] Audit Plugin: mysqld: /usr/local/mysql-5.6.22-linux-glibc2.5-x86_64/bin/mysqld (e1106bb336a206d1be38c365013523bc)
2015-01-29 16:49:49 64349 [Note] Audit Plugin: Couldn't find proper THD offsets for: 5.6.22-log
2015-01-29 16:49:49 64349 [ERROR] Plugin 'AUDIT' init function returned error.
2015-01-29 16:49:49 64349 [ERROR] Plugin 'AUDIT' registration as a AUDIT failed.
2015-01-29 16:49:49 64349 [Note] Shutting down plugin 'AUDIT'
2015-01-29 16:49:49 64349 [Note] Audit Plugin: deinit
 
I have a running mysql 5.5 and have audit running on it with plugin file for 5.5  placed in /usr/lib64/mysql/plugin/ and i have placed the audit plugin for 5.6 file in /usr/local/mysql/lib/plugin/.
all the binary files for mysql 5.6 are placed in /usr/local/mysql.

I am not sure where to place the plugin file for mysql 5.6.

**Comment by mysqlboy** [comment]
Find the plugin dir for the 5.6 instance. The 5.6 .so file should be placed
there for the instance to read it.

> show global variables like 'plugindir';

Depending on the version of MySQL and the flavour (percona, oracle,
mariadb) you might need to extract and supply the offsets in the my.cnf as
per the troubleshooting documentation.

**Comment by guylichtman** [comment]
From the log I see that you are using MySQL 5.6.22 with plugin version 1.0.6. This version doesn't contain offsets for 5.6.22. These offsets where added in 1.0.8 (see changelog: https://github.com/mcafee/mysql-audit/wiki/Changelog )  You can grap the latest dev-snapshot available here: https://bintray.com/mcafee/mysql-audit-plugin/dev-snapshot/ (make sure to download the binary for mysql-5.6).

**Comment by vishal08jan** [comment]
Hey

is see plugindir as blank 
mysql>
mysql>  show global variables like 'plugindir';
Empty set (0.00 sec)

**Comment by vishal08jan** [comment]
change it to plugin_dir and got this.
 plugin_dir                              /usr/local/mysql-5.6.22-linux-glibc2.5-x86_64/lib/plugin/ 
 and i already have placed the .so in this dir only.

[root@dev-shipping lib]# ll /usr/local/mysql-5.6.22-linux-glibc2.5-x86_64/lib/plugin/
total 3364
-rwxr-xr-x 1 7161 wheel   15437 Nov 21 11:33 adt_null.so
-rwxr-xr-x 1 7161 wheel   25619 Nov 21 11:33 auth.so
-rwxr-xr-x 1 7161 wheel   12364 Nov 21 11:33 auth_socket.so
-rwxr-xr-x 1 7161 wheel   25072 Nov 21 11:33 auth_test_plugin.so
-rw-r--r-- 1 7161 wheel     227 Nov 21 11:09 daemon_example.ini
drwxr-xr-x 2 root root     4096 Dec  3 16:50 debug
-rwxr-xr-x 1 7161 wheel  568171 Nov 21 11:33 innodb_engine.so
-rwxrwxrwx 1 root root  1252100 Jan 29 16:38 libaudit_plugin.so
-rwxr-xr-x 1 7161 wheel   42633 Nov 21 11:33 libdaemon_example.so
-rwxr-xr-x 1 7161 wheel  584183 Nov 21 11:33 libmemcached.so
-rwxr-xr-x 1 7161 wheel   17539 Nov 21 11:33 mypluglib.so
-rwxr-xr-x 1 7161 wheel   18151 Nov 21 11:33 qa_auth_client.so
-rwxr-xr-x 1 7161 wheel   23798 Nov 21 11:33 qa_auth_interface.so
-rwxr-xr-x 1 7161 wheel   12926 Nov 21 11:33 qa_auth_server.so
-rwxr-xr-x 1 7161 wheel  416913 Nov 21 11:33 semisync_master.so
-rwxr-xr-x 1 7161 wheel  250766 Nov 21 11:33 semisync_slave.so
-rwxr-xr-x 1 7161 wheel  139172 Nov 21 11:33 validate_password.so

**Comment by vishal08jan** [comment]
@guylichtman : Good catch. worked like a charm

@mysqlboy : Thanks to you too for quick support.

**Comment by guylichtman** [comment]
Closing the issue. If you have any further questions, feel free to open a new issue.
